env:
  global:
    - secure: "ir41AQtkicWViYb3j6QLwX9QkSJZA6/ufi/5r3PCAOzMm9tL6krQp5OQeOePS7vDtbSWVhuH2U8yiPUnWL8mfILeGsV7+sWW9mKRwPeFqgT8y6VheEvLM75firNx4siKpSR8rh+htrSSNl61hMe7n5RnNqwHHYntDrR9GcYYyO8="

language: csharp
sudo: required
before_script:
    - sudo pip2 install --upgrade pip
    - sudo pip2 install astroid==1.3.8
    - sudo pip2 install pylint==1.4.4
    - sudo pip2 install buildbot==0.8.12
    - sudo pip2 install requests
    - EC2PBOTMASTERIP=dummy make -C performancebot pylint
    - npm i -g webpack@1.12.2
    - npm i -g tslint@2.5.1
    - npm i -g eslint@1.1.0 # force this version until newer version than 1.3.1 is available (https://github.com/eslint/eslint/issues/3591)
    - make -C front-end
    - make -C front-end lint
    - make -C accredit/cloud-code lint
    - bash ./deploy-github-pages.sh

solution: tools/tools.sln
install:
    - (cd tools && bash ../performancebot/utils/nugethack.sh)
script:
    - xbuild /p:Configuration=Release /target:compare tools/tools.sln
    - xbuild /p:Configuration=Release /target:DbTool tools/tools.sln
    - xbuild /p:Configuration=Release /target:Accreditize tools/tools.sln
    - xbuild /p:Configuration=Release /target:Parse2Postgres tools/tools.sln
    - xbuild /p:Configuration=Release /target:xtcloghelper tools/tools.sln
    - xbuild /p:Configuration=Debug /target:compare tools/tools.sln
    - xbuild /p:Configuration=Debug /target:DbTool tools/tools.sln
    - xbuild /p:Configuration=Debug /target:Accreditize tools/tools.sln
    - xbuild /p:Configuration=Debug /target:Parse2Postgres tools/tools.sln
    - xbuild /p:Configuration=Debug /target:xtcloghelper tools/tools.sln
